Uc 04
henrikalbrecht/I05-Virtuelle-Maschinen pull request #117
Opened 2024-03-30 11:49 UTC by clemens29

First draft of UC04.

2024-03-30 19:45 UTC, don-ny requested changes
Wireframes find ich cool! (nur die Überschriften)

2024-03-30 19:45 UTC, don-ny commented on docs/requirements/images/uc04_ext_wireframe.png
Header heißt hier noch "Übersicht - Verwaltung..."

sollte aber "Templates - Verwaltung..." heißen

2024-03-30 19:45 UTC, don-ny commented on docs/requirements/images/uc04_wireframe.png
Header heißt hier noch "Übersicht - Verwaltung..."

sollte aber "Templates - Verwaltung..." heißen

2024-03-30 19:45 UTC, don-ny commented on docs/requirements/use_case_04.inc.adoc
Die Wireframes zeigen die section "VM Templates", in der Textbeschreibung sind aber die Email Templates als Bsp. genommen.
Vorschlag:
- "VM Template anlegen" als basic flow (ist fast copy&paste)
- jetzigen "Email Template anlegen" basic flow als zusätzlichen Alternativablauf hinzufügen

...ergibt insgesamt 4 Abläufe

2024-04-01 17:38 UTC, henrikalbrecht commented
Sollte der Standardablauf nciht so sein, dass lediglich ein Tenplate aus der Liste ausgewählt wird? Und das Anlegen eines neuen Templates wäre ebenso ein alternativer Ablauf?

2024-04-01 17:59 UTC, henrikalbrecht commented
DIe Templates sollen ja eine einfache copy paste Variante sein um diese zu schnell zu versenden. Wäre dann nicht in der Liste der Templates ein "copy betreff" und "copy Inhalt" sinnvoll um dies einfach zu ermöglichen?

2024-04-02 07:50 UTC, don-ny commented
> DIe Templates sollen ja eine einfache copy paste Variante sein um diese zu schnell zu versenden. Wäre dann nicht in der Liste der Templates ein "copy betreff" und "copy Inhalt" sinnvoll um dies einfach zu ermöglichen?

aktuell ist die Logik so gedacht, dass du, wie in UC03 zu sehen, einen Button hast, mit dem du den Email-Versand an eine Projektgruppe initiieren kannst. Man klickt auf den Button, wählt das Email-Template aus einer Liste aus und dann öffnet sich die vorbereitete Email in Outlook o.ä.

Und um ein Template aus der Liste auswählen zu können, muss man natürlich auch Templates anlegen können... dafür ist der Use-Case gedacht.

2024-04-02 15:36 UTC, don-ny approved these changes

2024-04-02 15:36 UTC, merged