Uc 05
henrikalbrecht/I05-Virtuelle-Maschinen pull request #118
Opened 2024-03-30 11:51 UTC by clemens29

First draft of UC05.

2024-03-30 19:53 UTC, don-ny requested changes
Überschriften in den Wireframes

und... ich glaube du hast die Wireframes vertauscht... UC05 ist VM Templates, UC 04 Email... die Grafiken zeigen aber genau das Vertauschte

2024-03-30 19:53 UTC, don-ny commented on docs/requirements/images/uc05_ext_wireframe.png
Überschrift ist:"Übersicht - Verwaltung..."
Überschrift soll:"Templates - Verwaltung..."

2024-03-30 19:53 UTC, don-ny commented on docs/requirements/images/uc05_wireframe.png
Überschrift ist:"Übersicht - Verwaltung..."
Überschrift soll:"Templates - Verwaltung..."

2024-04-01 17:57 UTC, henrikalbrecht commented
DIe Templates sollen ja eine einfache copy paste Variante sein um diese zu schnell zu versenden. Wäre dann nicht in der Liste der Templates ein "copy betreff" und "copy Inhalt" sinnvoll um dies einfach zu ermöglichen?

2024-04-02 15:38 UTC, merged