Wireframe UC01, UC03 hochgeladen
henrikalbrecht/I05-Virtuelle-Maschinen pull request #53
Opened 2023-12-17 07:31 UTC by Julius0123456789

Wireframes von Use Case Modell 01, 03 als PNG. in docs/requirements/image hochgeladen.

2023-12-17 17:03 UTC, don-ny commented on docs/requirements/images/Wireframe UC01 - Initial.png
- "VM-Datenbank" umbenennen in "Vergabe von Virtuellen Maschinen"

2023-12-17 17:12 UTC, don-ny requested changes
siehe individuelle Kommentare an den Grafiken

2023-12-17 17:12 UTC, don-ny commented on docs/requirements/images/Wireframe UC03 - Initial.png
- "Anforderungen von Studenten" umbenennen in "Vergabe von Virtuellen Maschinen"

UC03 beschäftigt sich damit, wie VMs an Projektteams vergeben (zugewiesen) werden.
(Ich klicke eine VM; Ich bekomme die Möglichkeit etwas einzutragen (bspw. einen Teamnamen, den Status etc.); Ich habe einen Button zum speichern)

Das Wireframe sollte eine Ergänzung zur Beschreibung von UC03 sein, damit man sich besser vorstellen kann, was der Nutzer auf dem display später mal sehen könnte.

**Vorschlag:** erst UC03 als Text ausarbeiten, dann das Wireframe überarbeiten und darauf anpassen

2023-12-18 07:44 UTC, henrikalbrecht commented
> Wireframes von Use Case Modell 01, 03 als PNG. in docs/requirements/image hochgeladen.

Mir gefällt die Beschreibung des PR :)
Vorbildlich!

2023-12-18 19:45 UTC, don-ny commented
@Julius0123456789 zusätzlich zu den Kommentaren oben:
- Einbindung der Wireframe Bilder in die Dateien use_case_01.inc.adoc und use_case_03.inc.adoc
--> Bilder kommen in docs/requirements/images/
--> wie die Verlinkung geht, siehe use-case_model.adoc (die vs-Code Vorschau zeigt das Bild an, der Browser aber nicht - das ist normal... s. Screenshots)

<img width="839" alt="Screenshot_Web" src="https://github.com/henrikalbrecht/I05-Virtuelle-Maschinen/assets/71487824/6044db0c-dfa1-4321-8fb3-3fc2cdc4eb4b">
.
<img width="1081" alt="Screenshot_vscode" src="https://github.com/henrikalbrecht/I05-Virtuelle-Maschinen/assets/71487824/676eeaf1-0c49-477b-8ef9-aa30bb6eb5f2">

2023-12-18 20:48 UTC, don-ny approved these changes
passt soweit

2023-12-18 20:48 UTC, merged