Uc3 glossar
henrikalbrecht/I05-Virtuelle-Maschinen pull request #54
Opened 2023-12-17 13:53 UTC by stony02

Use Case 3 Discription

2023-12-17 16:58 UTC, don-ny commented
1) Use case heißt nicht so, wie er im use-case-model definiert ist
2) Irgendwelche Vermischungen von use-case 1 und use-case 3 ganz am Anfang?
3) Unnötige Abschnitte löschen
4) kein Standardablauf definiert??
5) Wireframe einbinden

**s. Vorlesung 6 - Spezifikation mit Use Cases** (bspw. Folien 5, 7, 8) anschauen und noch mal von Grund auf überarbeiten

**Gutes Use-Case Beispiel hier:**
https://github.com/Schmiddl99/experimenteverwaltung-i2/blob/main/Dokumentationen/requirements/use_case_02.inc.adoc

2023-12-17 16:59 UTC, don-ny requested changes
1) Use case heißt nicht so, wie er im use-case-model definiert ist
2) Irgendwelche Vermischungen von use-case 1 und use-case 3 ganz am Anfang?
3) Unnötige Abschnitte löschen
4) kein Standardablauf definiert??
5) Wireframe einbinden

**s. Vorlesung 6 - Spezifikation mit Use Cases** (bspw. Folien 5, 7, 8) anschauen und noch mal von Grund auf überarbeiten

**Gutes Use-Case Beispiel hier:**
https://github.com/Schmiddl99/experimenteverwaltung-i2/blob/main/Dokumentationen/requirements/use_case_02.inc.adoc

2023-12-18 07:49 UTC, henrikalbrecht commented
Glossar welches du noch pushen wolltest fehlt -> PR Beschreibung passt nicht mit Inhalt zusammen.
Die Kurzbeschreibung klingt wie copy pastet und beschreibt nicht den use case sondern in gewisser weise das gesamte Projekt. 
Bitte nutze die Beispiele aus dem Opal (Paul hat einen verlinkt), die Vorlesung zu dem Thema und die Praktikumsunterlagen zu Überarbeitung.
Weiterhin stimme ich mit allen Punkten von Paul überein!

2023-12-19 05:50 UTC, don-ny requested changes
see individual comments

2023-12-19 05:50 UTC, don-ny commented on docs/requirements/use_case_03.inc.adoc
>  === Vorbedingungen
- Nutzer muss angemeldet sein

2023-12-19 05:50 UTC, don-ny commented on docs/requirements/use_case_03.inc.adoc
> +1. Nutzer hat Zugriff auf Verwaltungsmöglichkeiten
Gehört nicht zum Standardablauf, sondern ist Vorbedingung

2023-12-19 05:50 UTC, don-ny commented on docs/requirements/use_case_03.inc.adoc
> +2. Nutzer weist Änderung zu
vorher: Nutzer muss eine VM auswählen

2024-01-03 15:38 UTC, henrikalbrecht requested changes
I really like the wireframe for uc3. There is a slight mistake in line 47. Take a look at that please. The rest is very good :)

2024-01-03 15:45 UTC, henrikalbrecht approved these changes

2024-01-03 15:45 UTC, merged