Risklist_version_1
henrikalbrecht/I05-Virtuelle-Maschinen pull request #63
Opened 2023-12-29 14:04 UTC by arshactually2

Updated and formatted the risk_list_version1,  have to merge the risklist branch.

2024-01-14 10:33 UTC, don-ny requested changes
see individual comments

2024-01-14 10:33 UTC, don-ny commented on docs/project_management/resources/Risk_list_v1.csv
> +9,Workshop f�r alle mit Github,Limited understanding of Github among team members,Limited understanding of Github may hinder effective collaboration.,Provide Github tutorials and training sessions,,T
please check the risk list for "Umlaute" and change them in the following manner:
ü becomes ue
ä becomes ae etc.

2024-01-14 10:33 UTC, don-ny commented on docs/project_management/resources/Risk_list_v1.csv
> +,,,,,,,,,,,,
please add the risk of a team member leaving the team

2024-01-17 21:00 UTC, arshactually2 commented on docs/project_management/resources/Risk_list_v1.csv
> +,,,,,,,,,,,,
Completed the risklist and made all the required changes

2024-01-17 21:40 UTC, don-ny commented on docs/project_management/resources/Risk_list_v1.csv
> +,,,,,,,,,,,,
@arshactually2 the requested changes should have been pushed to the original "risklist" branch instead of a new one
we now have 2 different risklist branches with one of the branches containing the changes that were requested within the other branch.
@henrikalbrecht what's a good approach here?

2024-01-20 16:25 UTC, henrikalbrecht commented on docs/project_management/resources/Risk_list_v1.csv
> +,,,,,,,,,,,,
merging both individual branches together and then mergin that into main.

2024-01-21 06:40 UTC, don-ny approved these changes

2024-01-21 06:40 UTC, merged