Erste Überarbeitung des Glossars
henrikalbrecht/I05-Virtuelle-Maschinen pull request #83
Opened 2024-01-18 09:30 UTC by Julius0123456789

Ein Paar Begriffe wurden entfernt und die Beschreibungen überarbeitet.

2024-01-20 16:36 UTC, henrikalbrecht requested changes
Please take a closer look at the following Definitions:

- Docker Container
- Frameworks
- PostgreSQL Datenbank
- Open Source Datenbank? (Why is this in the List)

2024-01-21 12:45 UTC, don-ny requested changes
add _ORM_ to the list (we are using this term in architecture notebook)

You can find explanations here:
[Wikipedia (English)](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping)
[Wikipedia (German)](https://de.wikipedia.org/wiki/Objektrelationale_Abbildung)

2024-01-21 15:29 UTC, Julius0123456789 commented
Kommentare wurden Überarbeitet. Habe mich schwer getan, die Definitionen zu formulieren, ich hoffe ich habe die Bedeutung getroffen. Außerdem ist bei den Abkürzungen noch "UP" hingeschrieben worden aber ausgeblendet. Was hat es damit auf sich?

2024-01-21 16:01 UTC, don-ny requested changes
- [ ] Korrektur Docker-Container
- [ ] Korrektur Framework
- [ ] Korrektur Repository
- [ ] Update Merge
- [x] Korrektur VMware Cluster
- [x] Korrektur PostgreSQL
- [x] Vorschlag bei RAM
- [x] Vorschlag bei VM
- [x] Korrektur bei ORM

bitte hinzufügen: 
- [ ] RDBMS (wird in SQL erwähnt)
- [ ] Datenbankmanagementsystem (= DBMS)
- [ ] Git

UP bezieht sich wohl auf "Unified Process"... also in Anlehnung an OpenUP (Open Unified Process)

2024-01-21 16:01 UTC, don-ny commented on docs/requirements/glossary.adoc
> +| Docker-Container | Enthält, im vergleich zur VM, nur alle nötigen Resourcen, zur Ausführung einer bestimmten Software. Lässt sich leicht als Datei transportieren und installieren. |
```suggestion
| Docker-Container | Enthält, im vergleich zur VM, nur alle nötigen Resourcen die zur Ausführung einer bestimmten Software benötigt werden. Er lässt sich leicht als Datei transportieren und installieren. | 
```

2024-01-22 13:31 UTC, don-ny requested changes
- [x] bei Django ist Text abhanden gekommen

hinzufügen (Infos [hier](https://www.talend.com/de/resources/was-ist-rest-api/)):
- [x] REST
- [x] API
- [x] REST-API
- [ ] GET
- [ ] POST
- [x] JSON
- [ ] Client-Server-Architektur
- [x] Server

2024-01-22 13:31 UTC, don-ny commented on docs/requirements/glossary.adoc
> +| Django | Django ist ein leistungsstarkes |
Hier ist irgendwo Text abhanden gekommen

2024-01-24 16:01 UTC, don-ny approved these changes

2024-01-24 16:31 UTC, henrikalbrecht approved these changes

2024-01-24 16:31 UTC, merged