Refined Use cases
henrikalbrecht/I05-Virtuelle-Maschinen pull request #97
Opened 2024-01-24 20:00 UTC by clemens29

- refined use cases according to Paul's notes
- added red state to wireframe_01

2024-01-24 20:16 UTC, don-ny requested changes
please re-export the uc01 wireframewith quality set to 300dpi

all other work looks **very** good - really thorough job! 🫶

2024-01-24 20:16 UTC, don-ny commented on docs/requirements/images/uc01_wireframe.png
please re-export with quality set to 300dpi

2024-01-24 20:51 UTC, henrikalbrecht commented
Great work!

2024-01-25 16:13 UTC, don-ny approved these changes

2024-01-25 16:14 UTC, merged